// Code generated by protoc-gen-api-client. DO NOT EDIT.
package crypto

import (
	fmt "fmt"
	strings "strings"
)

const kindTLSProtocol = "TLSProtocol"

func (e TLSProtocol_Enum) MarshalText() (text []byte, err error) {
	s := e.String()
	if strings.HasPrefix(s, "TLS_PROTOCOL_ENUM_") {
		s = s[18:]
	}
	return []byte(s), nil
}

func (e *TLSProtocol_Enum) UnmarshalText(text []byte) error {
	repr := string(text)
	val, ok := TLSProtocol_Enum_value[repr]
	if !ok {
		if !strings.HasPrefix(repr, "TLS_PROTOCOL_ENUM_") {
			repr = "TLS_PROTOCOL_ENUM_" + repr
			val, ok = TLSProtocol_Enum_value[repr]
		}
	}
	if !ok {
		return fmt.Errorf("unrecognized enum TLSProtocol_Enum value %q", repr)
	}
	*e = TLSProtocol_Enum(val)
	return nil
}
