// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.22.3
// source: lib/proto/crypto/tls.proto

package crypto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLSProtocol_Enum int32

const (
	TLSProtocol_DEFAULT TLSProtocol_Enum = 0
	TLSProtocol_TLS_1_0 TLSProtocol_Enum = 1
	TLSProtocol_TLS_1_1 TLSProtocol_Enum = 2
	TLSProtocol_TLS_1_2 TLSProtocol_Enum = 3
	TLSProtocol_TLS_1_3 TLSProtocol_Enum = 4
)

// Enum value maps for TLSProtocol_Enum.
var (
	TLSProtocol_Enum_name = map[int32]string{
		0: "DEFAULT",
		1: "TLS_1_0",
		2: "TLS_1_1",
		3: "TLS_1_2",
		4: "TLS_1_3",
	}
	TLSProtocol_Enum_value = map[string]int32{
		"DEFAULT": 0,
		"TLS_1_0": 1,
		"TLS_1_1": 2,
		"TLS_1_2": 3,
		"TLS_1_3": 4,
	}
)

func (x TLSProtocol_Enum) Enum() *TLSProtocol_Enum {
	p := new(TLSProtocol_Enum)
	*p = x
	return p
}

func (x TLSProtocol_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TLSProtocol_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_proto_crypto_tls_proto_enumTypes[0].Descriptor()
}

func (TLSProtocol_Enum) Type() protoreflect.EnumType {
	return &file_lib_proto_crypto_tls_proto_enumTypes[0]
}

func (x TLSProtocol_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TLSProtocol_Enum.Descriptor instead.
func (TLSProtocol_Enum) EnumDescriptor() ([]byte, []int) {
	return file_lib_proto_crypto_tls_proto_rawDescGZIP(), []int{0, 0}
}

type TLSProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TLSProtocol) Reset() {
	*x = TLSProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_crypto_tls_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLSProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSProtocol) ProtoMessage() {}

func (x *TLSProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_crypto_tls_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSProtocol.ProtoReflect.Descriptor instead.
func (*TLSProtocol) Descriptor() ([]byte, []int) {
	return file_lib_proto_crypto_tls_proto_rawDescGZIP(), []int{0}
}

var File_lib_proto_crypto_tls_proto protoreflect.FileDescriptor

var file_lib_proto_crypto_tls_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x2f, 0x74, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0b, 0x54, 0x4c, 0x53, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x22, 0x47, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x4c, 0x53, 0x5f,
	0x31, 0x5f, 0x30, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x4c, 0x53, 0x5f, 0x31, 0x5f, 0x31,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x4c, 0x53, 0x5f, 0x31, 0x5f, 0x32, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x4c, 0x53, 0x5f, 0x31, 0x5f, 0x33, 0x10, 0x04, 0x42, 0x28, 0x5a, 0x26,
	0x72, 0x2e, 0x75, 0x6e, 0x64, 0x2e, 0x73, 0x2f, 0x64, 0x65, 0x76, 0x73, 0x65, 0x63, 0x6f, 0x70,
	0x73, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x3b,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_proto_crypto_tls_proto_rawDescOnce sync.Once
	file_lib_proto_crypto_tls_proto_rawDescData = file_lib_proto_crypto_tls_proto_rawDesc
)

func file_lib_proto_crypto_tls_proto_rawDescGZIP() []byte {
	file_lib_proto_crypto_tls_proto_rawDescOnce.Do(func() {
		file_lib_proto_crypto_tls_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_proto_crypto_tls_proto_rawDescData)
	})
	return file_lib_proto_crypto_tls_proto_rawDescData
}

var file_lib_proto_crypto_tls_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lib_proto_crypto_tls_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lib_proto_crypto_tls_proto_goTypes = []interface{}{
	(TLSProtocol_Enum)(0), // 0: crypto.TLSProtocol.Enum
	(*TLSProtocol)(nil),   // 1: crypto.TLSProtocol
}
var file_lib_proto_crypto_tls_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_proto_crypto_tls_proto_init() }
func file_lib_proto_crypto_tls_proto_init() {
	if File_lib_proto_crypto_tls_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_proto_crypto_tls_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TLSProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_proto_crypto_tls_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_proto_crypto_tls_proto_goTypes,
		DependencyIndexes: file_lib_proto_crypto_tls_proto_depIdxs,
		EnumInfos:         file_lib_proto_crypto_tls_proto_enumTypes,
		MessageInfos:      file_lib_proto_crypto_tls_proto_msgTypes,
	}.Build()
	File_lib_proto_crypto_tls_proto = out.File
	file_lib_proto_crypto_tls_proto_rawDesc = nil
	file_lib_proto_crypto_tls_proto_goTypes = nil
	file_lib_proto_crypto_tls_proto_depIdxs = nil
}
