// Code generated by protoc-gen-api-client. DO NOT EDIT.
package crypto

import (
	context "context"
	diag "github.com/hashicorp/terraform-plugin-framework/diag"
)

type TLSProtocolResourceModel struct {
}

// FromProto imports field values from protobuf message
func (m *TLSProtocolResourceModel) FromProto(r *TLSProtocol) (_ *TLSProtocolResourceModel, err error) {
	if m == nil {
		m = new(TLSProtocolResourceModel)
	}
	return m, nil
}

type TLSProtocolResourceTFModel struct {
}

// ToProto converts the model to the corresponding protobuf struct
func (m *TLSProtocolResourceTFModel) ToProto(ctx context.Context) (*TLSProtocol, diag.Diagnostics) {
	if m == nil {
		return nil, nil
	}
	r := &TLSProtocol{}
	return r, nil
}
