// Code generated by protoc-gen-api. DO NOT EDIT.
package crypto

import (
	runtime "github.com/ubikasec/terraform-provider-ubika/internal/api/runtime"
)

var GroupVersion = runtime.GroupVersion{
	Group:   "",
	Version: "crypto",
}
