// Code generated by protoc-gen-api. DO NOT EDIT.
package v1beta

import (
	grpc "google.golang.org/grpc"
)

// Client aggregate all gRPC services' clients
type Client interface {
	Workflow() WorkflowSvcClient
	OpenAPI() OpenAPISvcClient
	ExceptionProfile() ExceptionProfileSvcClient
	ErrorDocument() ErrorDocumentSvcClient
	TLSConfiguration() TLSConfigurationSvcClient
	TLSMaterialInternal() TLSMaterialInternalSvcClient
	IPBlacklist() IPBlacklistSvcClient
	Asset() AssetSvcClient
}

// client implements Client
type client struct {
	exceptionProfileSvc    ExceptionProfileSvcClient
	errorDocumentSvc       ErrorDocumentSvcClient
	tLSConfigurationSvc    TLSConfigurationSvcClient
	tLSMaterialInternalSvc TLSMaterialInternalSvcClient
	iPBlacklistSvc         IPBlacklistSvcClient
	assetSvc               AssetSvcClient
	workflowSvc            WorkflowSvcClient
	openAPISvc             OpenAPISvcClient
}

func NewGRPCClient(conn *grpc.ClientConn) Client {
	assetSvcClient := NewAssetSvcClient(conn)
	workflowSvcClient := NewWorkflowSvcClient(conn)
	openAPISvcClient := NewOpenAPISvcClient(conn)
	exceptionProfileSvcClient := NewExceptionProfileSvcClient(conn)
	errorDocumentSvcClient := NewErrorDocumentSvcClient(conn)
	tLSConfigurationSvcClient := NewTLSConfigurationSvcClient(conn)
	tLSMaterialInternalSvcClient := NewTLSMaterialInternalSvcClient(conn)
	iPBlacklistSvcClient := NewIPBlacklistSvcClient(conn)
	return &client{
		exceptionProfileSvc:    exceptionProfileSvcClient,
		errorDocumentSvc:       errorDocumentSvcClient,
		tLSConfigurationSvc:    tLSConfigurationSvcClient,
		tLSMaterialInternalSvc: tLSMaterialInternalSvcClient,
		iPBlacklistSvc:         iPBlacklistSvcClient,
		assetSvc:               assetSvcClient,
		workflowSvc:            workflowSvcClient,
		openAPISvc:             openAPISvcClient,
	}
}

func (s *client) Asset() AssetSvcClient {
	return s.assetSvc
}
func (s *client) Workflow() WorkflowSvcClient {
	return s.workflowSvc
}
func (s *client) OpenAPI() OpenAPISvcClient {
	return s.openAPISvc
}
func (s *client) ExceptionProfile() ExceptionProfileSvcClient {
	return s.exceptionProfileSvc
}
func (s *client) ErrorDocument() ErrorDocumentSvcClient {
	return s.errorDocumentSvc
}
func (s *client) TLSConfiguration() TLSConfigurationSvcClient {
	return s.tLSConfigurationSvc
}
func (s *client) TLSMaterialInternal() TLSMaterialInternalSvcClient {
	return s.tLSMaterialInternalSvc
}
func (s *client) IPBlacklist() IPBlacklistSvcClient {
	return s.iPBlacklistSvc
}

// compile-time assertion
var _ Client = &client{}
