// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.22.3
// source: lib/proto/api/annotations.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NamespacePermission namespace permission ordered from minimum to full access
type NamespacePermission int32

const (
	NamespacePermission_NAMESPACE_PERMISSION_UNSPECIFIED NamespacePermission = 0
	NamespacePermission_NAMESPACE_PERMISSION_READ_ONLY   NamespacePermission = 1
	NamespacePermission_NAMESPACE_PERMISSION_WRITE       NamespacePermission = 2
)

// Enum value maps for NamespacePermission.
var (
	NamespacePermission_name = map[int32]string{
		0: "NAMESPACE_PERMISSION_UNSPECIFIED",
		1: "NAMESPACE_PERMISSION_READ_ONLY",
		2: "NAMESPACE_PERMISSION_WRITE",
	}
	NamespacePermission_value = map[string]int32{
		"NAMESPACE_PERMISSION_UNSPECIFIED": 0,
		"NAMESPACE_PERMISSION_READ_ONLY":   1,
		"NAMESPACE_PERMISSION_WRITE":       2,
	}
)

func (x NamespacePermission) Enum() *NamespacePermission {
	p := new(NamespacePermission)
	*p = x
	return p
}

func (x NamespacePermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NamespacePermission) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_proto_api_annotations_proto_enumTypes[0].Descriptor()
}

func (NamespacePermission) Type() protoreflect.EnumType {
	return &file_lib_proto_api_annotations_proto_enumTypes[0]
}

func (x NamespacePermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NamespacePermission.Descriptor instead.
func (NamespacePermission) EnumDescriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{0}
}

type OrganisationPermission int32

const (
	OrganisationPermission_ORGANISATION_PERMISSION_UNSPECIFIED OrganisationPermission = 0
	OrganisationPermission_ORGANISATION_PERMISSION_OWNER       OrganisationPermission = 1
)

// Enum value maps for OrganisationPermission.
var (
	OrganisationPermission_name = map[int32]string{
		0: "ORGANISATION_PERMISSION_UNSPECIFIED",
		1: "ORGANISATION_PERMISSION_OWNER",
	}
	OrganisationPermission_value = map[string]int32{
		"ORGANISATION_PERMISSION_UNSPECIFIED": 0,
		"ORGANISATION_PERMISSION_OWNER":       1,
	}
)

func (x OrganisationPermission) Enum() *OrganisationPermission {
	p := new(OrganisationPermission)
	*p = x
	return p
}

func (x OrganisationPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganisationPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_proto_api_annotations_proto_enumTypes[1].Descriptor()
}

func (OrganisationPermission) Type() protoreflect.EnumType {
	return &file_lib_proto_api_annotations_proto_enumTypes[1]
}

func (x OrganisationPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganisationPermission.Descriptor instead.
func (OrganisationPermission) EnumDescriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{1}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_KIND        MessageType = 1
	MessageType_MESSAGE_TYPE_LIST        MessageType = 2
	MessageType_MESSAGE_TYPE_SPEC        MessageType = 3
	MessageType_MESSAGE_TYPE_STATUS      MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_KIND",
		2: "MESSAGE_TYPE_LIST",
		3: "MESSAGE_TYPE_SPEC",
		4: "MESSAGE_TYPE_STATUS",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_KIND":        1,
		"MESSAGE_TYPE_LIST":        2,
		"MESSAGE_TYPE_SPEC":        3,
		"MESSAGE_TYPE_STATUS":      4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_proto_api_annotations_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_lib_proto_api_annotations_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{2}
}

type RusService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *RusService) Reset() {
	*x = RusService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_api_annotations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RusService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RusService) ProtoMessage() {}

func (x *RusService) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_api_annotations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RusService.ProtoReflect.Descriptor instead.
func (*RusService) Descriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *RusService) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Authz defines authorizations required to access the method.
// A `OR` is applied between each property.
// eg: if roles is defined and namespace_permission too, a user who has a role in `roles` can access the method,
// also a user which has the required `namespace_permission` can access it too. They don't require to have both.
type Authz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// any_authenticated, if `true` any user that passed the authentication middleware can access the method.
	AnyAuthenticated bool `protobuf:"varint,1,opt,name=any_authenticated,json=anyAuthenticated,proto3" json:"any_authenticated,omitempty"`
	// authn_types is the authentication method used: "apikey", "internalkey" (any of them must mach).
	AuthnTypes []string `protobuf:"bytes,2,rep,name=authn_types,json=authnTypes,proto3" json:"authn_types,omitempty"`
	// roles of the authenticated user: "acme", "logforwarder" "xds" (any of them must match).
	Roles []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	// namespace_permission the minimum namespace permission a user must have.
	// eg: if NAMESPACE_PERMISSION_READ_ONLY, a user with write access can also access this namespace method.
	NamespacePermission NamespacePermission `protobuf:"varint,4,opt,name=namespace_permission,json=namespacePermission,proto3,enum=api.NamespacePermission" json:"namespace_permission,omitempty"`
	// organisation_permission the minimum organisation permission a user must have.
	OrganisationPermission OrganisationPermission `protobuf:"varint,5,opt,name=organisation_permission,json=organisationPermission,proto3,enum=api.OrganisationPermission" json:"organisation_permission,omitempty"`
}

func (x *Authz) Reset() {
	*x = Authz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_api_annotations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authz) ProtoMessage() {}

func (x *Authz) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_api_annotations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authz.ProtoReflect.Descriptor instead.
func (*Authz) Descriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Authz) GetAnyAuthenticated() bool {
	if x != nil {
		return x.AnyAuthenticated
	}
	return false
}

func (x *Authz) GetAuthnTypes() []string {
	if x != nil {
		return x.AuthnTypes
	}
	return nil
}

func (x *Authz) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Authz) GetNamespacePermission() NamespacePermission {
	if x != nil {
		return x.NamespacePermission
	}
	return NamespacePermission_NAMESPACE_PERMISSION_UNSPECIFIED
}

func (x *Authz) GetOrganisationPermission() OrganisationPermission {
	if x != nil {
		return x.OrganisationPermission
	}
	return OrganisationPermission_ORGANISATION_PERMISSION_UNSPECIFIED
}

type RusMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Authz  *Authz `protobuf:"bytes,3,opt,name=authz,proto3" json:"authz,omitempty"`
}

func (x *RusMethod) Reset() {
	*x = RusMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_api_annotations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RusMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RusMethod) ProtoMessage() {}

func (x *RusMethod) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_api_annotations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RusMethod.ProtoReflect.Descriptor instead.
func (*RusMethod) Descriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *RusMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RusMethod) GetAuthz() *Authz {
	if x != nil {
		return x.Authz
	}
	return nil
}

type RusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=api.MessageType" json:"type,omitempty"`
	// collection_itself true when the object is the Collection itself
	// this means there can be only one object of this kind in the
	// collection, and it must be named like the collection itself.
	CollectionItself bool `protobuf:"varint,2,opt,name=collection_itself,json=collectionItself,proto3" json:"collection_itself,omitempty"`
}

func (x *RusMessage) Reset() {
	*x = RusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_proto_api_annotations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RusMessage) ProtoMessage() {}

func (x *RusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_lib_proto_api_annotations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RusMessage.ProtoReflect.Descriptor instead.
func (*RusMessage) Descriptor() ([]byte, []int) {
	return file_lib_proto_api_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *RusMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *RusMessage) GetCollectionItself() bool {
	if x != nil {
		return x.CollectionItself
	}
	return false
}

var file_lib_proto_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*RusService)(nil),
		Field:         74295727,
		Name:          "api.rus_service",
		Tag:           "bytes,74295727,opt,name=rus_service",
		Filename:      "lib/proto/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RusMethod)(nil),
		Field:         74295728,
		Name:          "api.rus_method",
		Tag:           "bytes,74295728,opt,name=rus_method",
		Filename:      "lib/proto/api/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*RusMessage)(nil),
		Field:         74295729,
		Name:          "api.rus_msg",
		Tag:           "bytes,74295729,opt,name=rus_msg",
		Filename:      "lib/proto/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional api.RusService rus_service = 74295727;
	E_RusService = &file_lib_proto_api_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional api.RusMethod rus_method = 74295728;
	E_RusMethod = &file_lib_proto_api_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional api.RusMessage rus_msg = 74295729;
	E_RusMsg = &file_lib_proto_api_annotations_proto_extTypes[2]
)

var File_lib_proto_api_annotations_proto protoreflect.FileDescriptor

var file_lib_proto_api_annotations_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0a, 0x52, 0x75, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x8e, 0x02, 0x0a, 0x05, 0x41,
	0x75, 0x74, 0x68, 0x7a, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x6e, 0x79, 0x5f, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x61, 0x6e, 0x79, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x14, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x13, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x54, 0x0a, 0x17, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x16, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x09, 0x52,
	0x75, 0x73, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x20, 0x0a, 0x05, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x7a, 0x52, 0x05, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x22, 0x5f, 0x0a, 0x0a, 0x52, 0x75, 0x73, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x11,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x74, 0x73, 0x65, 0x6c,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x74, 0x73, 0x65, 0x6c, 0x66, 0x2a, 0x7f, 0x0a, 0x13, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x24, 0x0a, 0x20, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x50, 0x45,
	0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x4e, 0x41, 0x4d, 0x45, 0x53, 0x50,
	0x41, 0x43, 0x45, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x4e, 0x41,
	0x4d, 0x45, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x10, 0x02, 0x2a, 0x64, 0x0a, 0x16, 0x4f, 0x72,
	0x67, 0x61, 0x6e, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x23, 0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x53, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a,
	0x1d, 0x4f, 0x52, 0x47, 0x41, 0x4e, 0x49, 0x53, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x45,
	0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x10, 0x01,
	0x2a, 0x89, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1c, 0x0a, 0x18, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x11, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4b,
	0x49, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x50, 0x45,
	0x43, 0x10, 0x03, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x04, 0x3a, 0x54, 0x0a, 0x0b,
	0x72, 0x75, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xaf, 0xd3, 0xb6,
	0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0a, 0x72, 0x75, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x3a, 0x50, 0x0a, 0x0a, 0x72, 0x75, 0x73, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xb0, 0xd3, 0xb6, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x75, 0x73, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x09, 0x72, 0x75, 0x73, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x3a, 0x4c, 0x0a, 0x07, 0x72, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x12,
	0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0xb1, 0xd3, 0xb6, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x52, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x72, 0x75, 0x73, 0x4d,
	0x73, 0x67, 0x42, 0x25, 0x5a, 0x23, 0x72, 0x2e, 0x75, 0x6e, 0x64, 0x2e, 0x73, 0x2f, 0x64, 0x65,
	0x76, 0x73, 0x65, 0x63, 0x6f, 0x70, 0x73, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lib_proto_api_annotations_proto_rawDescOnce sync.Once
	file_lib_proto_api_annotations_proto_rawDescData = file_lib_proto_api_annotations_proto_rawDesc
)

func file_lib_proto_api_annotations_proto_rawDescGZIP() []byte {
	file_lib_proto_api_annotations_proto_rawDescOnce.Do(func() {
		file_lib_proto_api_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_proto_api_annotations_proto_rawDescData)
	})
	return file_lib_proto_api_annotations_proto_rawDescData
}

var file_lib_proto_api_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_lib_proto_api_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lib_proto_api_annotations_proto_goTypes = []interface{}{
	(NamespacePermission)(0),            // 0: api.NamespacePermission
	(OrganisationPermission)(0),         // 1: api.OrganisationPermission
	(MessageType)(0),                    // 2: api.MessageType
	(*RusService)(nil),                  // 3: api.RusService
	(*Authz)(nil),                       // 4: api.Authz
	(*RusMethod)(nil),                   // 5: api.RusMethod
	(*RusMessage)(nil),                  // 6: api.RusMessage
	(*descriptorpb.ServiceOptions)(nil), // 7: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 8: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
}
var file_lib_proto_api_annotations_proto_depIdxs = []int32{
	0,  // 0: api.Authz.namespace_permission:type_name -> api.NamespacePermission
	1,  // 1: api.Authz.organisation_permission:type_name -> api.OrganisationPermission
	4,  // 2: api.RusMethod.authz:type_name -> api.Authz
	2,  // 3: api.RusMessage.type:type_name -> api.MessageType
	7,  // 4: api.rus_service:extendee -> google.protobuf.ServiceOptions
	8,  // 5: api.rus_method:extendee -> google.protobuf.MethodOptions
	9,  // 6: api.rus_msg:extendee -> google.protobuf.MessageOptions
	3,  // 7: api.rus_service:type_name -> api.RusService
	5,  // 8: api.rus_method:type_name -> api.RusMethod
	6,  // 9: api.rus_msg:type_name -> api.RusMessage
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	7,  // [7:10] is the sub-list for extension type_name
	4,  // [4:7] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_lib_proto_api_annotations_proto_init() }
func file_lib_proto_api_annotations_proto_init() {
	if File_lib_proto_api_annotations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_proto_api_annotations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RusService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_api_annotations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_api_annotations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RusMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_proto_api_annotations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_proto_api_annotations_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_lib_proto_api_annotations_proto_goTypes,
		DependencyIndexes: file_lib_proto_api_annotations_proto_depIdxs,
		EnumInfos:         file_lib_proto_api_annotations_proto_enumTypes,
		MessageInfos:      file_lib_proto_api_annotations_proto_msgTypes,
		ExtensionInfos:    file_lib_proto_api_annotations_proto_extTypes,
	}.Build()
	File_lib_proto_api_annotations_proto = out.File
	file_lib_proto_api_annotations_proto_rawDesc = nil
	file_lib_proto_api_annotations_proto_goTypes = nil
	file_lib_proto_api_annotations_proto_depIdxs = nil
}
