// Code generated by protoc-gen-api. DO NOT EDIT.
package metav1beta

import (
	fmt "fmt"
	strings "strings"
)

const KindTypeMeta = "TypeMeta"
const KindObjectMeta = "ObjectMeta"
const KindOrganisationedObjectMeta = "OrganisationedObjectMeta"
const KindListMeta = "ListMeta"
const KindUnstructuredObject = "UnstructuredObject"
const KindWatchEvent = "WatchEvent"
const KindListOptions = "ListOptions"
const KindGetOptions = "GetOptions"
const KindPatchOptions = "PatchOptions"
const KindDeleteOptions = "DeleteOptions"
const KindWatchOptions = "WatchOptions"

func (e WatchEvent_Type) MarshalText() (text []byte, err error) {
	s := e.String()
	if strings.HasPrefix(s, "WATCH_EVENT_TYPE_") {
		s = s[17:]
	}
	return []byte(s), nil
}

func (e *WatchEvent_Type) UnmarshalText(text []byte) error {
	repr := string(text)
	val, ok := WatchEvent_Type_value[repr]
	if !ok {
		if !strings.HasPrefix(repr, "WATCH_EVENT_TYPE_") {
			repr = "WATCH_EVENT_TYPE_" + repr
			val, ok = WatchEvent_Type_value[repr]
		}
	}
	if !ok {
		return fmt.Errorf("unrecognized enum WatchEvent_Type value %q", repr)
	}
	*e = WatchEvent_Type(val)
	return nil
}
