// Code generated by protoc-gen-api. DO NOT EDIT.
package metav1beta

import (
	runtime "github.com/ubikasec/terraform-provider-ubika/internal/api/runtime"
)

var GroupVersion = runtime.GroupVersion{
	Group:   "meta",
	Version: "v1beta",
}
