// Code generated by protoc-gen-api-client. DO NOT EDIT.
package v1beta

import (
	runtime "github.com/ubikasec/terraform-provider-ubika/internal/api/runtime"
)

var GroupVersion = runtime.GroupVersion{
	Group:   "assets.ubika.io",
	Version: "v1beta",
}
